name: Workflow Dispatcher

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write

jobs:
  check-changes:
    runs-on: ubuntu-24.04
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Hello World
      run: echo "Hello, World!"